### ISSUE TITLE
Spamming info 

### ISSUE THREAD

**Issue by Phelms215** [budak7273/Woodcutter#1]
This datapack keeps spamming chat logs, how can I turn this function off? 

![image](https://user-images.githubusercontent.com/3196320/178060787-73622b64-dde7-4198-be87-0b12b1eff070.png)

**Comment by budak7273** [comment]
(Including @gike12 @Mulinix because they liked the original post)

How often is the message being printed? It should only appear once each time you open the woodcutter. This is on purpose because there is no "recipe book" support for the stonecutter yet; there is no way to see all of the available recipes in-game.

If you want to stop this you can run `/scoreboard objectives remove wc_stonecutter_interact` to remove the watcher. `/function woodcutter:init` will bring it back
